import{a as v,S as P,i as s}from"./assets/vendor-B5nsgUv9.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))i(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const c of o.addedNodes)c.tagName==="LINK"&&c.rel==="modulepreload"&&i(c)}).observe(document,{childList:!0,subtree:!0});function n(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerPolicy&&(o.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?o.credentials="include":e.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function i(e){if(e.ep)return;e.ep=!0;const o=n(e);fetch(e.href,o)}})();document.querySelector(".gallery");const E="https://pixabay.com/api/",$="54694924-0cbff3df35e5124e95f47eab6";async function d(t,r){const n={key:$,q:t,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:15,page:r};return(await v.get(E,{params:n})).data}const f=document.querySelector(".loader"),m=document.querySelector(".gallery");let B=new P(".gallery a");function y(t){const r=t.map(({webformatURL:n,largeImageURL:i,tags:e,likes:o,views:c,comments:b,downloads:q})=>`
    <li class="gallery-item">
        <a href="${i}">
            <img src="${n}" alt="${e}" ></a>
        <div class="info">
     <p>${o}Likes</p>
            <p> ${c}Views</p>
            <p> ${b}Comments</p>
        <p> ${q}Downloads</p>
    </div>
     </li>
   `).join("");m.insertAdjacentHTML("beforeend",r),B.refresh()}const h=document.querySelector(".load-more");function M(){m.innerHTML=""}function g(){f.classList.remove("is-hidden")}function p(){f.classList.add("is-hidden")}function L(){h.classList.remove("is-hidden")}function l(){h.classList.add("is-hidden")}let a=1,w="",u=0;const S=15,O=document.querySelector(".form");O.addEventListener("submit",x);async function x(t){t.preventDefault();const r=t.target.elements["search-text"].value.trim();if(r===""){s.warning({message:"Please enter a search query!"});return}w=r,a=1,M(),l(),g();try{const n=await d(r,a);if(u=n.totalHits,n.hits.length===0){s.error({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"});return}y(n.hits),a*S<u?L():(l(),s.info({message:"We're sorry, but you've reached the end of search results."}))}catch(n){console.log(n),s.error({message:"Something went wrong. Try again later."})}finally{p()}}const A=document.querySelector(".load-more");A.addEventListener("click",T);async function T(){a++,l(),g();try{const t=await d(w,a);y(t.hits),C(),a*S<u?L():(l(),s.info({message:"We're sorry, but you've reached the end of search results."}))}catch(t){s.error({message:"Something went wrong. Try again later."}),console.log(t)}finally{p()}}const _=document.querySelector(".gallery");function C(){const t=_.firstElementChild;if(!t)return;const{height:r}=t.getBoundingClientRect();window.scrollBy({top:r*2,behavior:"smooth"})}
//# sourceMappingURL=index.js.map
