import{a as q,S as v,i as c}from"./assets/vendor-B5nsgUv9.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))a(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const i of t.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&a(i)}).observe(document,{childList:!0,subtree:!0});function n(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function a(e){if(e.ep)return;e.ep=!0;const t=n(e);fetch(e.href,t)}})();document.querySelector(".gallery");const P="https://pixabay.com/api/",E="54694924-0cbff3df35e5124e95f47eab6";async function u(r,o){const n={key:E,q:r,image_type:"photo",orientation:"horizontal",safesearch:"true",PER_PAGE:15,page:o};return(await q.get(P,{params:n})).data}const f=document.querySelector(".loader"),m=document.querySelector(".gallery");let M=new v(".gallery a");function y(r){const o=r.map(({webformatURL:n,largeImageURL:a,tags:e,likes:t,views:i,comments:S,downloads:b})=>`
    <li class="gallery-item">
        <a href="${a}">
            <img src="${n}" alt="${e}" ></img></a>
        <div class="info">
     <p>${t}Likes</p>
            <p> ${i}Views</p>
            <p> ${S}Comments</p>
        <p> ${b}Downloads</p>
    </div>
     </li>
   `).join("");m.insertAdjacentHTML("beforeend",o),M.refresh()}const g=document.querySelector(".load-more");function $(){m.innerHTML=""}function h(){f.classList.remove("is-hidden")}function p(){f.classList.add("is-hidden")}function A(){g.classList.remove("load-more-hidden")}function l(){g.classList.add("load-more-hidden")}let s=1,L="",d=0;const w=15,O=document.querySelector(".form");O.addEventListener("submit",x);async function x(r){r.preventDefault();const o=r.target.elements["search-text"].value.trim();if(o===""){c.warning({message:"Please enter a search query!"});return}L=o,s=1,$(),l(),h();try{const n=await u(o,s);y(n.hits),d=n.totalHits,s*w<d?A():(l(),c.info({message:"We're sorry, but you've reached the end of search results."}))}catch(n){c.error({message:"Something went wrong. Try again later."}),console.log(n)}finally{p()}}const B=document.querySelector(".load-more");B.addEventListener("click",T);async function T(){h(),s++;try{const r=await u(L,s);y(r.hits),s*w>=d&&(l(),c.info({message:"We're sorry, but you've reached the end of search results."}))}catch(r){c.error({message:"Something went wrong. Try again later."}),console.log(r)}finally{p()}}document.querySelector(".gallery");
//# sourceMappingURL=index.js.map
