import{a as q,S as v,i as c}from"./assets/vendor-B5nsgUv9.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))a(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const i of o.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&a(i)}).observe(document,{childList:!0,subtree:!0});function s(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerPolicy&&(o.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?o.credentials="include":e.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function a(e){if(e.ep)return;e.ep=!0;const o=s(e);fetch(e.href,o)}})();document.querySelector(".gallery");const P="https://pixabay.com/api/",E="54694924-0cbff3df35e5124e95f47eab6";async function d(t,r){const s={key:E,q:t,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:15,page:r};return(await q.get(P,{params:s})).data}const f=document.querySelector(".loader"),m=document.querySelector(".gallery");let $=new v(".gallery a");function y(t){const r=t.map(({webformatURL:s,largeImageURL:a,tags:e,likes:o,views:i,comments:w,downloads:b})=>`
    <li class="gallery-item">
        <a href="${a}">
            <img src="${s}" alt="${e}" ></a>
        <div class="info">
     <p>${o}Likes</p>
            <p> ${i}Views</p>
            <p> ${w}Comments</p>
        <p> ${b}Downloads</p>
    </div>
     </li>
   `).join("");m.insertAdjacentHTML("beforeend",r),$.refresh()}const h=document.querySelector(".load-more");function B(){m.innerHTML=""}function g(){f.classList.remove("is-hidden")}function M(){f.classList.add("is-hidden")}function p(){h.classList.remove("is-hidden")}function l(){h.classList.add("is-hidden")}let n=1,L="",u=0;const S=15,O=document.querySelector(".form");O.addEventListener("submit",x);async function x(t){t.preventDefault();const r=t.target.elements["search-text"].value.trim();if(r===""){c.warning({message:"Please enter a search query!"});return}L=r,n=1,B(),l(),g();try{const s=await d(r,n);if(u=s.totalHits,s.hits.length===0){c.error({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"});return}y(s.hits),n*S<u?p():(l(),c.info({message:"We're sorry, but you've reached the end of search results."}))}catch{error}}const A=document.querySelector(".load-more");A.addEventListener("click",_);async function _(){n++,l(),g();try{const t=await d(L,n);y(t.hits),H(),n*S<u?p():(l(),c.info({message:"We're sorry, but you've reached the end of search results."}))}catch(t){c.error({message:"Something went wrong. Try again later."}),console.log(t)}finally{M()}}const C=document.querySelector(".gallery");function H(){const t=C.firstElementChild;if(!t)return;const{height:r}=t.getBoundingClientRect();window.scrollBy({top:r*2,behavior:"smooth"})}
//# sourceMappingURL=index.js.map
